CREATE DATABASE IF NOT EXISTS wms_estoque CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wms_estoque;

CREATE TABLE items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL, barcode VARCHAR(80) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL DEFAULT 'Geral', risk VARCHAR(50) NOT NULL,
  turnover VARCHAR(50) NOT NULL, packaging VARCHAR(100) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 0, minimum_stock INT UNSIGNED NOT NULL DEFAULT 0,
  location_code VARCHAR(80) NOT NULL, segment VARCHAR(160) NOT NULL DEFAULT 'Geral',
  active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE stock_movements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
  movement_type VARCHAR(50) NOT NULL, quantity INT UNSIGNED NOT NULL, operator_name VARCHAR(120) NOT NULL,
  condition_note VARCHAR(120) NULL, reason TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_movement_item FOREIGN KEY (item_id) REFERENCES items(id)
);
CREATE TABLE picking_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_code VARCHAR(40) NOT NULL UNIQUE,
  strategy VARCHAR(80) NOT NULL, item_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL,
  customer_order VARCHAR(100) NOT NULL, status VARCHAR(40) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL, CONSTRAINT fk_picking_item FOREIGN KEY (item_id) REFERENCES items(id)
);
CREATE TABLE fulfillment_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, client_name VARCHAR(160) NOT NULL, client_cnpj VARCHAR(24) NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL, recipient VARCHAR(160) NOT NULL,
  invoice_number VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fulfillment_item FOREIGN KEY (item_id) REFERENCES items(id)
);
CREATE TABLE inventory_adjustments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
  previous_quantity INT UNSIGNED NOT NULL, counted_quantity INT UNSIGNED NOT NULL,
  conversion_factor INT UNSIGNED NOT NULL, final_quantity INT UNSIGNED NOT NULL,
  reason TEXT NOT NULL, operator_name VARCHAR(120) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_adjustment_item FOREIGN KEY (item_id) REFERENCES items(id)
);
CREATE TABLE audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, operator_name VARCHAR(120) NOT NULL,
  action_description VARCHAR(255) NOT NULL, record_hash VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE item_documents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
  file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT UNSIGNED NOT NULL,
  file_data LONGBLOB NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_document_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
